### PR TITLE
Create financial fraud

### PR DESCRIPTION
**Pull request by velzie**

### CODE REVIEW

**Comment by Percslol** [comment]
this is pushing our closed source changes to git, i dont think this pr should be public

**Comment by genericness** [comment]
@velzie you forgot the tax fraud

**Comment by genericness** [comment]
https://pad.nixnet.services/s/udjbqtomr

**Comment by e9x** [comment]
no idea wtf this pr is. closing

**Comment by thonkinator** [comment]
i have this feeling that this "e9x" fellow does have an idea what this pr is

**Comment by e9x** [comment]
> i have this feeling that this "e9x" fellow does have an idea what this pr is

I'm not involved with any sort of financial fraud.

**Comment by BomberFish** [comment]
> > i have this feeling that this "e9x" fellow does have an idea what this pr is
> 
> I'm not involved with any sort of financial fraud.

[citation needed]

**Comment by e9x** [comment]
> [citation needed]
@BomberFish 

What do I cite? I haven't made any payments to anyone. All revenue that I've made off HU has been handled entirely by me. My personal finances are none of your business. I also won't tolerate any harassment. My mental health has gone to shit as a result of all these baseless accusations. Yes I struggle with communication. No, I do not engage in any fraud. Sorry you don't keep up with me, or even bother to hear my side of the story.

**Comment by BomberFish** [comment]
holy yapping, batman

**Pull request closed without merging**
